{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.shalkan",
    "module": "logging-starter",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 11844,
          "sha512": "a62d41a473deabc103e43e706154f53258f0fa51b54463e6090112ddf542ef3a8e9bef52c9926991245e1620e5fdd9c607594525e893b5120d0c98940c3f439f",
          "sha256": "4c8ee84d3a2f0bf9e8a6903b92b31031b7a0486a99b630a35641ef98ccdafcca",
          "sha1": "03f8bf6ecb44e7c0b6e253a9facde5faa0e55773",
          "md5": "de8bc0e6939605849a2a0e269b3d61a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 11844,
          "sha512": "a62d41a473deabc103e43e706154f53258f0fa51b54463e6090112ddf542ef3a8e9bef52c9926991245e1620e5fdd9c607594525e893b5120d0c98940c3f439f",
          "sha256": "4c8ee84d3a2f0bf9e8a6903b92b31031b7a0486a99b630a35641ef98ccdafcca",
          "sha1": "03f8bf6ecb44e7c0b6e253a9facde5faa0e55773",
          "md5": "de8bc0e6939605849a2a0e269b3d61a2"
        }
      ]
    }
  ]
}
