{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.shalkan",
    "module": "logging-starter",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 9860,
          "sha512": "0a7a77f4e04bec217f69498187f288e2c13f3a5a04b29ac1267955bac930a0acaa52c4383d47ee0272c788108905fc9f7a3d059485117c7dc414270b7f3b6e54",
          "sha256": "7520a58df016a4be0bdb9075c8fd9c0302f90c3f181211d4a9f4036151d3c9d4",
          "sha1": "17be94c97565a213a7f504608d38023bfa59010b",
          "md5": "b675ea5916ca0b573a2262e9450cbdae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 9860,
          "sha512": "0a7a77f4e04bec217f69498187f288e2c13f3a5a04b29ac1267955bac930a0acaa52c4383d47ee0272c788108905fc9f7a3d059485117c7dc414270b7f3b6e54",
          "sha256": "7520a58df016a4be0bdb9075c8fd9c0302f90c3f181211d4a9f4036151d3c9d4",
          "sha1": "17be94c97565a213a7f504608d38023bfa59010b",
          "md5": "b675ea5916ca0b573a2262e9450cbdae"
        }
      ]
    }
  ]
}
