{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.shalkan",
    "module": "logging-starter",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 11648,
          "sha512": "ddae81b6e36151b0c53009dcd8bfe9e01da341eea1a602709443e19b21d7399aa598d8a46a69128e73e43ebde0accc6e2adab87331b33c3739507a9301d4d68a",
          "sha256": "1896e6fc06a1cc474945e25c3fcc12c1579daf7f00501209483aeb07582d5aba",
          "sha1": "91f1546d033f1a8373acb3a2be5fdaf2f359cce1",
          "md5": "21d0fa85e76734f1099fbace87892381"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 11648,
          "sha512": "ddae81b6e36151b0c53009dcd8bfe9e01da341eea1a602709443e19b21d7399aa598d8a46a69128e73e43ebde0accc6e2adab87331b33c3739507a9301d4d68a",
          "sha256": "1896e6fc06a1cc474945e25c3fcc12c1579daf7f00501209483aeb07582d5aba",
          "sha1": "91f1546d033f1a8373acb3a2be5fdaf2f359cce1",
          "md5": "21d0fa85e76734f1099fbace87892381"
        }
      ]
    }
  ]
}
