{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.shalkan",
    "module": "logging-starter",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 11914,
          "sha512": "15cc89bfd397ed314f9b06d240f9a01f172a83526db68893fdaf6c6f2fcac68b5a56fb1f61328be54b77c87d69a00febd0dad9bff34e10bd953e2ce03bf77d46",
          "sha256": "792df9158c1eb92f4d72dead411b604cefb024097f32438c0fe86bea72cc92e2",
          "sha1": "1a5b1406e75e5a3ae6035aa2b142e1b7d4d995e3",
          "md5": "1c6485d729dc29898d14cc0c9c29519f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 11914,
          "sha512": "15cc89bfd397ed314f9b06d240f9a01f172a83526db68893fdaf6c6f2fcac68b5a56fb1f61328be54b77c87d69a00febd0dad9bff34e10bd953e2ce03bf77d46",
          "sha256": "792df9158c1eb92f4d72dead411b604cefb024097f32438c0fe86bea72cc92e2",
          "sha1": "1a5b1406e75e5a3ae6035aa2b142e1b7d4d995e3",
          "md5": "1c6485d729dc29898d14cc0c9c29519f"
        }
      ]
    }
  ]
}
